version: 2
jobs:
  build:
    working_directory: ~/transtats
    docker:
      - image: registry.fedoraproject.org/fedora:latest
        environment:
          DATABASE_URL: postgresql://root@localhost/transtats?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: transtats
    steps:
      - run:
          name: Install system dependencies
          command: dnf -y install gcc findutils git python3 python3-pip python3-devel sudo redhat-rpm-config koji cpio patch make openssh-server openssl-devel
      - checkout
      - run:
          name: Setup environment
          command: |
            sudo pip3 install virtualenv
            virtualenv --python=/usr/bin/python3.7 --system-site-packages .venv
            pip3 install -r requirements/ci.txt
      - run:
          name: Run tests
          command: |
            source ~/transtats/.venv/bin/activate
            make lint test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
