version: '3'
services:
  database:
    image: postgres 
    environment:
      POSTGRES_DB: transtats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  transtats:
    build: 
      context: ./transtats
    image: transtats/transtats-sa:latest
    environment:
      DATABASE_HOST: database
    ports:
      - 8080:8080
    entrypoint: ["wait-for-it.sh", "database:5432", "--", "transtats.sh"]
    depends_on:
      - database
